#!/usr/bin/bash

if ! sudo -u workshop --login command -v gradle >/dev/null 2>&1; then
  workshopctl set-health --code="gradle-not-on-path" error "Binary 'gradle' not available on the \$PATH."
  exit 0
fi

workshopctl set-health okay
